Error Mapping section update
There are two errors when creating the flow for the two requests using AnyPoint Studio Version: 7.11.1: 
MuleRuntimeException: Could not find ErrorType for the given identifier: 'API_1'
MuleRuntimeException: Could not find ErrorType for the given identifier: 'API_2'

Updating the Error Type in the Error Continue and in Error Propagate to API_2:API_2 and API_1:API_1 respectively will fix the issue. Currently the screenshot https://docs.mulesoft.com/mule-runtime/4.4/_images/error-handling-mappings.png also misleads that the error type is API_1 or API_2 instead of API_1:API_1 and API_2:API_2. It is also good to update both Requests display name to API 1 and API 2. I have an updated screenshot as well, https://i.ibb.co/3SyGbv7/error-mappings.png.